name: Auto Release from Release Branch PR

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  release:
    if: >
      github.event.pull_request.merged == true &&
      startsWith(github.event.pull_request.head.ref, 'releases/And-')
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Provide Git identity
        run: |
          git config --global user.email "rahul.sood@gumtreegroup.com.au"
          git config --global user.name "Rahul Sood"

      - name: Extract version from branch
        run: |
          BRANCH=${{ github.event.pull_request.head.ref }}
          SAFE=${BRANCH#releases/And-}
          SAFE=${SAFE%%-*}
          echo "VERSION=$SAFE" >> $GITHUB_ENV

      - name: Fetch all tags
        run: git fetch --tags

      - name: Compute previous release tag
        id: prev
        run: |
          PREV=$(git tag --sort=-creatordate \
            | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' \
            | grep -v "^${{ env.VERSION }}\$" \
            | head -n1 || true)
          echo "PREVIOUS_TAG=$PREV" >> $GITHUB_ENV
          echo "::set-output name=previous_tag::$PREV"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION }}
          name: Release ${{ env.VERSION }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
