name: Draft & Publish Android Release Tag

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

permissions:
  contents: write
  id-token: write

jobs:
  release:
    # Only proceed if:
    # - A PR was merged (handles merge, rebase, squash)
    # - OR it's a push event to 'main'
    if: |
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true) ||
      (github.event_name == 'push')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Determine source branch
        id: source
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "SOURCE_BRANCH=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV
          else
            # Lookup the PR from the latest commit for push events
            PR_DATA=$(gh api repos/${{ github.repository }}/commits/${{ github.sha }}/pulls --jq '.[0].head.ref')
            echo "SOURCE_BRANCH=$PR_DATA" >> $GITHUB_ENV
          fi
          echo "Detected source branch: $SOURCE_BRANCH"

      - name: Verify branch naming convention
        if: ${{ !startsWith(env.SOURCE_BRANCH, 'releases/And-') }}
        run: |
          echo "Source branch '${SOURCE_BRANCH}' does not start with 'releases/And-'. Skipping release flow."
          exit 0

      - name: Extract version
        run: |
          VERSION=${SOURCE_BRANCH#releases/And-}
          VERSION=${VERSION%%-*}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Computed VERSION = $VERSION"

      - name: Compute previous tag
        id: prev
        run: |
          PREV=$(git tag --sort=-creatordate \
            | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' \
            | grep -v "^${VERSION}$" \
            | head -n1 || true)
          echo "PREVIOUS_TAG=$PREV" >> $GITHUB_ENV

      - name: Create annotated tag & push
        run: |
          git tag -a "$VERSION" -m "Release $VERSION"
          git push origin "$VERSION"

      - name: Generate changelog
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fromTag: ${{ env.PREVIOUS_TAG }}
          toTag: ${{ env.VERSION }}
          writeToFile: false
          includeRefIssues: true
          useGitmojis: true
          reverseOrder: false
          includeInvalidCommits: true

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          name: "Release ${{ env.VERSION }}"
          body: ${{ steps.changelog.outputs.changes }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
