name: Create Release Tag

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g. 25.87.0)'
        required: true

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get previous tag
        id: prevtag
        run: |
          prev_tag=$(git describe --tags --abbrev=0)
          echo "PREVIOUS_TAG=$prev_tag" >> $GITHUB_ENV

      - name: Set current version
        run: echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV

      - name: Generate changelog
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fromTag: ${{ env.PREVIOUS_TAG }}
          toTag: ${{ env.VERSION }}
          writeToFile: false
          includeRefIssues: true
          useGitmojis: true
          reverseOrder: false
          includeInvalidCommits: true
          excludeTypes: ""

      - name: Prepare release body (rename heading)
        run: |
          mkdir -p dist
          # Save raw changelog
          cat > dist/RELEASE_BODY_RAW.md <<'EOF'
          ${{ steps.changelog.outputs.changes }}
          EOF
          
          # Replace 🛸 Other Changes with 🛸 What Changed
          sed 's/🛸 Other Changes/🛸 What Changed/g' dist/RELEASE_BODY_RAW.md > dist/RELEASE_BODY.md
          
          # Append Full Changelog link
          {
            echo "";
            echo "**[Full Changelog](https://github.com/${{ github.repository }}/compare/${{ env.PREVIOUS_TAG }}...${{ env.VERSION }})**";
          } >> dist/RELEASE_BODY.md

      - name: Create Git tag
        run: |
          git tag ${{ env.VERSION }}
          git push origin ${{ env.VERSION }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION }}
          body_path: dist/RELEASE_BODY.md
